name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install chromium
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "monkeytype-github-profile"
          entrypoint: "main.ts" # 📝 Update the entrypoint if necessary
          root: "." # 📝 Update the root if necessary
